# -*- coding: utf-8 -*-
"""Supermart-Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqkoOLdxmc9CIUGYlgTNonGFC6iq6d7U

**Importing the Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Reading CSV File**"""

df=pd.read_csv("/content/Supermart Grocery Sales - Retail Analytics Dataset.csv")
df.head()

"""**Other Details about the Dataset**"""

df.shape

df.size

df.columns

df.info()

df.index

"""**Data Cleaning**"""

df.isnull().sum()

df[df.duplicated]

"""**Data Preparation**"""

df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")

df['Order Date']

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month_name()
df["Date"] = df["Order Date"].dt.day

df.head(2)

df["Category"].value_counts()

df["Sub Category"].value_counts()

df.pivot_table(index="Year", columns="Category", values="Sales", aggfunc="sum")

df.pivot_table(index="Month", columns="Category", values="Sales", aggfunc="sum")

"""**Exploratory Data Analysis(EDA)**"""

plt.figure(figsize=(12, 6))
sns.countplot(data=df,x='Category',order=df["Category"].value_counts().index)
plt.title("No. of Products sold in each Category")
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(data=df,x='Sub Category',color='green',order=df["Sub Category"].value_counts().index)
plt.title("No. of Products sold in each Sub Category")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(data=df,x='City',color='orange',order=df["City"].value_counts().index)
plt.title("No. of Products sold in each City")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(data=df,x='Region',color='green',order=df["Region"].value_counts().index)
plt.title("No. of Products sold in each Region")
plt.show()

fig, ax = plt.subplots(figsize=(12, 6))
sns.countplot(data=df, x="Year", order=df["Year"].value_counts().index)
ax.set_title("No. of Products sold each Year")
ax.bar_label(ax.containers[0], fontsize=10)
plt.show()

fig, ax = plt.subplots(figsize=(12, 6))
sns.countplot(data=df, y="Month", color="red", order=df["Month"].value_counts().index)
ax.set_title("No. of Products sold each Month")
ax.bar_label(ax.containers[0], fontsize=10)
plt.show()

